spring:
  datasource:
    url: ${AUTH_SVC_DB_URL}
    username: ${AUTH_SVC_DB_USERNAME}
    password: ${AUTH_SVC_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
api:
  server:
    deployed: ${AUTH_SERVER_URL}
