package com.waya.wayaauthenticationservice.enums;

public enum OTPRequestType {
    EMAIL_VERIFICATION,
    PHONE_VERIFICATION,
    PIN_CHANGE_EMAIL,
    PIN_CHANGE_PHONE,
    PIN_RESET_EMAIL,
    PIN_RESET_PHONE,
    PIN_CREATE_EMAIL,
    PIN_CREATE_PHONE,
    PASSWORD_CHANGE_EMAIL,
    PASSWORD_CHANGE_PHONE,
    PASSWORD_RESET_EMAIL,
    PASSWORD_RESET_PHONE,
    ADMIN_VERIFICATION
}
